import { Model } from './types'

export const contractions: Array<Model> = [
  { short: "'aight", long: "alright" },
  { short: "ain't", long: "am not" },
  { short: "ain't", long: "did not" },
  { short: "ain't", long: "have not" },
  { short: "ain't", long: "has not" },
  { short: "ain't", long: "are not" },
  { short: "ain't", long: "is not" },
  { short: "amn't", long: "am not" },
  { short: "aren't", long: "are not" },
  { short: "can't", long: "cannot" },
  { short: "'cause", long: "because" },
  { short: "could've", long: "could have" },
  { short: "couldn't", long: "could not" },
  { short: "couldn't've", long: "could not have" },
  { short: "daren't", long: "dare not" },
  { short: "daren't", long: "dared not" },
  { short: "daresn't", long: "dare not" },
  { short: "dasn't", long: "dare not" },
  { short: "didn't", long: "did not" },
  { short: "doesn't", long: "does not" },
  { short: "don't", long: "do not" },
  { short: "don't", long: "does not" },
  { short: "dunno", long: "don't know" },
  { short: "dunno", long: "do not know" },
  { short: "d'ye", long: "do you" },
  { short: "d'ye", long: "did you" },
  { short: "e'er", long: "ever" },
  { short: "everybody's", long: "everybody is" },
  { short: "everyone's", long: "everyone is" },
  { short: "finna", long: "fixing to" },
  { short: "finna", long: "going to" },
  { short: "g'day", long: "good day" },
  { short: "gimme", long: "give me" },
  { short: "giv'n", long: "given" },
  { short: "gonna", long: "going to" },
  { short: "gon't", long: "go not" },
  { short: "gotta", long: "got to" },
  { short: "hadn't", long: "had not" },
  { short: "had've", long: "had have" },
  { short: "hasn't", long: "has not" },
  { short: "haven't", long: "have not" },
  { short: "he'd", long: "he had" },
  { short: "he'd", long: "he would" },
  { short: "he'll", long: "he shall" },
  { short: "he'll", long: "he will" },
  { short: "he's", long: "he has" },
  { short: "he's", long: "he is" },
  { short: "he've", long: "he have" },
  { short: "how'd", long: "how did" },
  { short: "how'd", long: "how would" },
  { short: "howdy", long: "how do you do" },
  { short: "howdy", long: "how do you fare" },
  { short: "how'll", long: "how will" },
  { short: "how're", long: "how are" },
  { short: "how's", long: "how has" },
  { short: "how's", long: "how is" },
  { short: "how's", long: "how does" },
  { short: "I'd", long: "I had" },
  { short: "I'd", long: "I would" },
  { short: "I'd've", long: "I would have" },
  { short: "I'll", long: "I shall" },
  { short: "I'll", long: "I will" },
  { short: "I'm", long: "I am" },
  { short: "I'm'a", long: "I am about to" },
  { short: "I'm'o", long: "I am going to" },
  { short: "innit", long: "is it not" },
  { short: "I've", long: "I have" },
  { short: "isn't", long: "is not" },
  { short: "it'd", long: "it would" },
  { short: "it'll", long: "it shall" },
  { short: "it'll", long: "it will" },
  { short: "it's", long: "it has" },
  { short: "it's", long: "it is" },
  { short: "iunno", long: "I don't know" },
  { short: "let's", long: "let us" },
  { short: "ma'am", long: "madam" },
  { short: "mayn't", long: "may not" },
  { short: "may've", long: "may have" },
  { short: "methinks", long: "me thinks" },
  { short: "mightn't", long: "might not" },
  { short: "might've", long: "might have" },
  { short: "mustn't", long: "must not" },
  { short: "mustn't've", long: "must not have" },
  { short: "must've", long: "must have" },
  { short: "needn't", long: "need not" },
  { short: "nal", long: "and all" },
  { short: "ne'er", long: "never" },
  { short: "o'clock", long: "of the clock" },
  { short: "o'er", long: "over" },
  { short: "ol'", long: "old" },
  { short: "oughtn't", long: "ought not" },
  { short: "shalln't", long: "shall not" },
  { short: "shan't", long: "shall not" },
  { short: "should've", long: "should have" },
  { short: "shouldn't", long: "should not" },
  { short: "shouldn't've", long: "should not have" },
  { short: "somebody's", long: "somebody has" },
  { short: "somebody's", long: "somebody is" },
  { short: "someone's", long: "someone has" },
  { short: "something's", long: "something has" },
  { short: "something's", long: "something is" },
  { short: "so're", long: "so are" },
  { short: "that'll", long: "that shall" },
  { short: "that're", long: "that are" },
  { short: "that's", long: "that has" },
  { short: "that's", long: "that is" },
  { short: "that'd", long: "that would" },
  { short: "that'd", long: "that had" },
  { short: "there'd", long: "there had" },
  { short: "there'd", long: "there would" },
  { short: "there'll", long: "there shall" },
  { short: "there'll", long: "there will" },
  { short: "there're", long: "there are" },
  { short: "there's", long: "there has" },
  { short: "there's", long: "there is" },
  { short: "these're", long: "these are" },
  { short: "these've", long: "these have" },
  { short: "they'd", long: "they had" },
  { short: "they'd", long: "they would" },
  { short: "they'll", long: "they shall" },
  { short: "they'll", long: "they will" },
  { short: "they're", long: "they are" },
  { short: "they're", long: "they were" },
  { short: "they've", long: "they have" },
  { short: "this's", long: "this has" },
  { short: "this's", long: "this is" },
  { short: "those're", long: "those are" },
  { short: "those've", long: "those have" },
  { short: "'tis", long: "it is" },
  { short: "to've", long: "to have" },
  { short: "'twas", long: "it was" },
  { short: "wanna", long: "want to" },
  { short: "wasn't", long: "was not" },
  { short: "we'd", long: "we had" },
  { short: "we'd", long: "we would" },
  { short: "we'd", long: "we did" },
  { short: "we'd've", long: "we would have" },
  { short: "we'll", long: "we shall" },
  { short: "we'll", long: "we will" },
  { short: "we're", long: "we are" },
  { short: "we've", long: "we have" },
  { short: "weren't", long: "were not" },
  { short: "what'd", long: "what did" },
  { short: "what'll", long: "what shall" },
  { short: "what'll", long: "what will" },
  { short: "what're", long: "what are" },
  { short: "what're", long: "what were" },
  { short: "what's", long: "what has" },
  { short: "what's", long: "what is" },
  { short: "what's", long: "what does" },
  { short: "what've", long: "what have" },
  { short: "when's", long: "when has" },
  { short: "when's", long: "when is" },
  { short: "where'd", long: "where did" },
  { short: "where'll", long: "where shall" },
  { short: "where'll", long: "where will" },
  { short: "where're", long: "where are" },
  { short: "where's", long: "where has" },
  { short: "where's", long: "where is" },
  { short: "where's", long: "where does" },
  { short: "where've", long: "where have" },
  { short: "which'd", long: "which had" },
  { short: "which'd", long: "which would" },
  { short: "which'll", long: "which shall" },
  { short: "which'll", long: "which will" },
  { short: "which're", long: "which are" },
  { short: "which's", long: "which has" },
  { short: "which's", long: "which is" },
  { short: "which've", long: "which have" },
  { short: "who'd", long: "who would" },
  { short: "who'd", long: "who had" },
  { short: "who'd", long: "who did" },
  { short: "who'd've", long: "who would have" },
  { short: "who'll", long: "who shall" },
  { short: "who'll", long: "who will" },
  { short: "who're", long: "who are" },
  { short: "who's", long: "who has" },
  { short: "who's", long: "who is" },
  { short: "who's", long: "who does" },
  { short: "who've", long: "who have" },
  { short: "why'd", long: "why did" },
  { short: "why're", long: "why are" },
  { short: "why's", long: "why has" },
  { short: "why's", long: "why is" },
  { short: "why's", long: "why does" },
  { short: "willn't", long: "will not" },
  { short: "won't", long: "will not" },
  { short: "wonnot", long: "will not" },
  { short: "would've", long: "would have" },
  { short: "wouldn't", long: "would not" },
  { short: "wouldn't've", long: "would not have" },
  { short: "y'all", long: "you all" },
  { short: "y'all'd've", long: "you all would have" },
  { short: "y'all'd'n've", long: "you all would not have" },
  { short: "y'all're", long: "you all are" },
  { short: "you'd", long: "you had" },
  { short: "you'd", long: "you would" },
  { short: "you'll", long: "you shall" },
  { short: "you'll", long: "you will" },
  { short: "you're", long: "you are" },
  { short: "you've", long: "you have" }
];
